### ISSUE TITLE
Make driver value configurable

### ISSUE THREAD

**Issue by MichaelPereira** [creativeview/mssql_system_dsn#1]
Hi,

First, thanks for laying the ground work for this module. As I looked at how to manage the ODBC configuration with puppet, I was pleased to see that I wasn't the first one to have this problem :)

However the current way to configure the ODBC DSN entries is not flexible enough, as the value for the driver may differ on different systems. For example, on the windows server 2012 machine were I want to run it, the driver value is C:\Windows\system32\SQLSRV32.dll but the current code does not allow me to put the value.

I will propose a change shortly, but I will need to setup my environment to test it

**Comment by creativeview** [comment]
Hi,
The module currently supports the native clients for MS SQL 2008 and 2012. It would need another option for $sql_version to allow the SQLSRV32.dll to be used. What database server are you wanting to use this with?

**Comment by MichaelPereira** [comment]
By default I only have one SQL Server driver installed the server I am configuring, which has the file `C:\Windows\system32\SQLSRV32.dll` associated for the Driver value.

But looking at other machines, there are ODBC settings for old SQL server versions (2005, 2008), MySQL as well as ORACLE, all with different paths for the driver, which is why I think that the `$driver` value should be customizable.

**Comment by creativeview** [comment]
It would also need to get the correct driver name so just providing the dll path($driver) would not be enough. Currently this module is just for MS SQL server. I could add support for MS SQL 2005.  

What database server are you needing to use this with?

**Comment by creativeview** [comment]
No feedback for a month so closing this off.
